# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/shared", nfs: true

  config.vm.define :python do |python|
    python.vm.box = "neito/centos7"
    python.vm.hostname = 'dev-python'
    python.vm.network :private_network, ip: '192.168.56.4'

    python.vm.provider :virtualbox do |vb|
      vb.name = "dev-python"
      vb.customize ["modifyvm", :id, "--memory", "512"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end

    python.vm.provision :shell, inline: <<-SCRIPT
mkdir /home/vagrant/.provisioned -p
if [ ! -f /home/vagrant/.provisioned/.python ]; then
  yum install -y python python34
  touch /home/vagrant/.provisioned/.python
else
  echo "Skipping Python installation..."
fi

if [ ! -f /home/vagrant/.provisioned/.pip ]; then
  curl --silent --location https://bootstrap.pypa.io/get-pip.py | python3
  touch /home/vagrant/.provisioned/.pip
else
  echo "Skipping Python Pip installation..."
fi

SCRIPT
  end
end
