# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/shared", nfs: true

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.define :php do |php|
    php.vm.box = "neito/centos7"
    php.vm.hostname = 'php.dev'
    php.vm.network :private_network, ip: '192.168.56.5'
    php.hostmanager.aliases = %w(example.dev)
    php.vm.provider :virtualbox do |vb|
      vb.name = "dev-php"
      vb.customize ["modifyvm", :id, "--memory", "512"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end

    php.vm.provision :shell, inline: <<-SCRIPT
mkdir /home/vagrant/.provisioned -p
if [ ! -f /home/vagrant/.provisioned/.php ]; then
  yum -y install httpd php php-mysql php-mcrypt php-fpm php-gd
  systemctl enable httpd.service
  systemctl restart httpd.service
  touch /home/vagrant/.provisioned/.php
else
  echo "Skipping PHP installation..."
fi

if [ ! -f /home/vagrant/.provisioned/.mariadb ]; then
cat <<-EOF >/etc/yum.repos.d/mariadb.repo
# MariaDB 10.1 CentOS repository list - created 2016-06-01 02:53 UTC
# # http://downloads.mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.1/centos7-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
EOF
  yum -y install MariaDB-server MariaDB-client
  touch /home/vagrant/.provisioned/.mariadb
else
  echo "Skipping MySQL installation..."
fi

if [ ! -f /home/vagrant/.provisioned/.composer ]; then
  curl -s https://getcomposer.org/installer | php
  touch /home/vagrant/.provisioned/.composer
else
  echo "Skipping Composer installation..."
fi

SCRIPT
  end
end
